#!/usr/bin/env bash
#
# lib/profile.sh — `vminv configure` and named-profile management (aws-cli-style).
#
# Profiles hold NON-SECRET per-environment config at
#   ~/.config/vminv/profiles/<name>.env   (mode 600)
# The vCenter password is never written there. At configure time you choose how
# the password is supplied at run time:
#   - prompt   : vminv asks interactively each run (default, most secure)
#   - env      : you export VCENTER_PASSWORD before running
#   - keyring  : stored in the OS secret store (libsecret/Keychain) if available
#
# Sourced by vminv; requires lib/common.sh.

# --- OS keyring (best-effort) -----------------------------------------------
keyring_backend() {
  if command -v secret-tool >/dev/null 2>&1; then echo secret-tool
  elif command -v security >/dev/null 2>&1; then echo security
  else echo none; fi
}
keyring_set() { # keyring_set <profile> <secret-on-stdin>
  local p="$1"
  case "$(keyring_backend)" in
    secret-tool) secret-tool store --label="vminv ${p}" service vminv profile "$p" >/dev/null 2>&1 ;;
    security)    local s; s="$(cat)"; security add-generic-password -U -s "vminv" -a "$p" -w "$s" >/dev/null 2>&1 ;;
    none) return 1 ;;
  esac
}
keyring_get() { # keyring_get <profile> -> secret on stdout (or non-zero)
  local p="$1"
  case "$(keyring_backend)" in
    secret-tool) secret-tool lookup service vminv profile "$p" 2>/dev/null ;;
    security)    security find-generic-password -s "vminv" -a "$p" -w 2>/dev/null ;;
    none) return 1 ;;
  esac
}

# --- Profile files ----------------------------------------------------------
profile_list() {
  local d; d="$(vminv_profiles_dir)"
  [ -d "$d" ] || { info "No profiles yet. Run: vminv configure"; return 0; }
  local f n
  for f in "$d"/*.env; do
    [ -e "$f" ] || continue
    n="$(basename "$f" .env)"
    printf '  %s\n' "$n"
  done
}

profile_show() {
  local f; f="$(vminv_profile_file "${1:-default}")"
  [ -f "$f" ] || die "Profile not found: ${1:-default} (${f})"
  # The profile holds no secrets, but redact defensively anyway.
  redact_register "${VCENTER_PASSWORD:-}"
  local line
  while IFS= read -r line; do printf '%s\n' "$(redact "$line")"; done <"$f"
  return 0
}

# Write a profile file from the PROFILE_VALUES associative array.
declare -A PROFILE_VALUES=()
write_profile() { # write_profile <name>
  local name="$1" dir f k
  dir="$(vminv_profiles_dir)"; f="$(vminv_profile_file "$name")"
  mkdir -p "$dir" || die "Cannot create ${dir}"
  {
    printf '# vminv profile "%s" — generated by `vminv configure`\n' "$name"
    printf '# Non-secret configuration only. The vCenter password is NOT stored here.\n'
    for k in "${CONFIG_KEYS[@]}"; do
      [ "$k" = "VCENTER_PASSWORD" ] && continue
      if [ -n "${PROFILE_VALUES[$k]+x}" ]; then
        printf '%s=%q\n' "$k" "${PROFILE_VALUES[$k]}"
      fi
    done
    [ -n "${PROFILE_VALUES[PASSWORD_SOURCE]+x}" ] && printf 'PASSWORD_SOURCE=%q\n' "${PROFILE_VALUES[PASSWORD_SOURCE]}"
  } >"$f"
  chmod 600 "$f"
  ok "Wrote profile '${name}' -> ${f}"
}

# Non-interactive configure: merge KEY=VALUE pairs into a profile and write it.
#   configure_apply <name> KEY=VAL [KEY=VAL ...]
configure_apply() {
  local name="$1"; shift
  PROFILE_VALUES=()
  local f; f="$(vminv_profile_file "$name")"
  if [ -f "$f" ]; then set -a; # shellcheck disable=SC1090
                       source "$f"; set +a; fi
  local k
  for k in "${CONFIG_KEYS[@]}"; do
    [ "$k" = "VCENTER_PASSWORD" ] && continue
    [ -n "${!k+x}" ] && PROFILE_VALUES["$k"]="${!k}"
  done
  [ -n "${PASSWORD_SOURCE:-}" ] && PROFILE_VALUES["PASSWORD_SOURCE"]="${PASSWORD_SOURCE}"
  local pair key val
  for pair in "$@"; do
    key="${pair%%=*}"; val="${pair#*=}"
    [ "$key" = "$pair" ] && die "$EX_USAGE" "--set expects KEY=VALUE (got '${pair}')"
    PROFILE_VALUES["$key"]="$val"
  done
  write_profile "$name"
}

# --- Interactive configure --------------------------------------------------
# _ask <var> <prompt> <default>  — read with a default shown in brackets.
_ask() {
  local __v="$1" prompt="$2" def="${3:-}" ans
  if [ -n "$def" ]; then printf '%s [%s]: ' "$prompt" "$def" >&2; else printf '%s: ' "$prompt" >&2; fi
  IFS= read -r ans || true
  [ -z "$ans" ] && ans="$def"
  printf -v "$__v" '%s' "$ans"
}
_ask_choice() { # _ask_choice <var> <prompt> <default> <opt1> <opt2> ...
  local __v="$1" prompt="$2" def="$3"; shift 3
  local -a opts=("$@"); local ans o valid
  while :; do
    printf '%s (%s) [%s]: ' "$prompt" "$(IFS='|'; echo "${opts[*]}")" "$def" >&2
    IFS= read -r ans || true; [ -z "$ans" ] && ans="$def"
    valid=0; for o in "${opts[@]}"; do [ "$ans" = "$o" ] && valid=1 && break; done
    if [ "$valid" -eq 1 ]; then break; fi
    printf '  ! "%s" is not one of: %s\n' "$ans" "$(IFS=' '; echo "${opts[*]}")" >&2
  done
  printf -v "$__v" '%s' "$ans"
}

cmd_configure() {
  local name="${1:-default}"
  info "Configuring vminv profile '${name}' (press Enter to keep the [default])."
  # preload existing values if the profile exists
  local existing; existing="$(vminv_profile_file "$name")"
  [ -f "$existing" ] && { set -a; # shellcheck disable=SC1090
                          source "$existing"; set +a; }

  local host user insecure dc cluster folder vmglob target perf out dest pwsrc
  _ask host    "vCenter host"                  "${VCENTER_HOST:-}"
  _ask user    "vCenter user"                  "${VCENTER_USER:-svc-vminv@vsphere.local}"
  _ask_choice insecure "Allow self-signed TLS" "${VCENTER_INSECURE:-false}" true false
  printf '\n  How should the vCenter PASSWORD be provided at run time?\n' >&2
  printf '    prompt  = vminv asks you each run (most secure; nothing stored)\n' >&2
  printf '    env     = you export $VCENTER_PASSWORD before running\n' >&2
  printf '    keyring = store it now in your OS keyring (libsecret/Keychain)\n' >&2
  printf '  (You do NOT type the password here unless you choose "keyring".)\n' >&2
  _ask_choice pwsrc "Password source"          "${PASSWORD_SOURCE:-prompt}" prompt env keyring
  _ask dc      "Scope: datacenter (blank=all)" "${SCOPE_DATACENTER:-}"
  _ask cluster "Scope: cluster (blank=all)"    "${SCOPE_CLUSTER:-}"
  _ask folder  "Scope: folder (blank=all)"     "${SCOPE_FOLDER:-}"
  _ask vmglob  "Scope: VM name glob (blank=all)" "${SCOPE_VM_GLOB:-}"
  _ask_choice target "Cloud target"            "${TARGET_PROVIDER:-aws}" aws azure gcp
  _ask perf    "Perf window (days)"            "${PERF_WINDOW_DAYS:-30}"
  _ask out     "Output directory"              "${OUTPUT_DIR:-./output}"
  _ask dest    "Upload destination (s3://, gs://, az://, sftp://, https://, path; blank=none)" "${UPLOAD_DEST:-}"

  PROFILE_VALUES=(
    [VCENTER_HOST]="$host" [VCENTER_USER]="$user" [VCENTER_INSECURE]="$insecure"
    [SCOPE_DATACENTER]="$dc" [SCOPE_CLUSTER]="$cluster" [SCOPE_FOLDER]="$folder" [SCOPE_VM_GLOB]="$vmglob"
    [TARGET_PROVIDER]="$target" [PERF_WINDOW_DAYS]="$perf" [OUTPUT_DIR]="$out"
    [UPLOAD_DEST]="$dest" [PASSWORD_SOURCE]="$pwsrc"
  )
  write_profile "$name"

  if [ "$pwsrc" = "keyring" ]; then
    if [ "$(keyring_backend)" = none ]; then
      warn "No OS keyring backend (secret-tool/security) found — falling back to runtime prompt."
    else
      local pw pw2
      printf 'vCenter password (stored in OS keyring): ' >&2; IFS= read -rs pw; echo >&2
      printf 'Confirm password: ' >&2; IFS= read -rs pw2; echo >&2
      if [ "$pw" = "$pw2" ] && [ -n "$pw" ]; then
        printf '%s' "$pw" | keyring_set "$name" && ok "Password stored in OS keyring." || warn "Keyring store failed; will prompt at runtime."
      else
        warn "Passwords did not match / empty — not stored. vminv will prompt at runtime."
      fi
    fi
  fi
  ok "Done. Use it with:  vminv --profile ${name} --dry-run"
}
